"""
Add 100 non-duplicate words to each of 準2級, 2級, 準1級, 1級.
"""
import json
import uuid
import shutil
import os

WATCH_JSON = "/Users/endoushougo/Python_pjs/EnglishWord/EnglishWord Watch App/Resources/words.json"
IOS_JSON   = "/Users/endoushougo/Python_pjs/EnglishWord/EnglishWordIOS/Resources/words.json"

with open(WATCH_JSON, encoding="utf-8") as f:
    words = json.load(f)

existing = set(w["english"].lower() for w in words)

# (english, japanese, category)
candidates = {
    "準2級": [
        # 動詞
        ("accomplish", "成し遂げる", "動詞"),
        ("affect", "影響を与える", "動詞"),
        ("allow", "許可する", "動詞"),
        ("arrange", "手配する", "動詞"),
        ("assist", "手伝う", "動詞"),
        ("avoid", "避ける", "動詞"),
        ("blame", "責める", "動詞"),
        ("borrow", "借りる", "動詞"),
        ("capture", "捕まえる", "動詞"),
        ("celebrate", "祝う", "動詞"),
        ("claim", "主張する", "動詞"),
        ("collect", "集める", "動詞"),
        ("combine", "組み合わせる", "動詞"),
        ("compare", "比較する", "動詞"),
        ("compete", "競争する", "動詞"),
        ("confirm", "確認する", "動詞"),
        ("connect", "つなぐ", "動詞"),
        ("contain", "含む", "動詞"),
        ("convince", "説得する", "動詞"),
        ("cooperate", "協力する", "動詞"),
        ("create", "作る", "動詞"),
        ("damage", "損傷を与える", "動詞"),
        ("decide", "決める", "動詞"),
        ("decorate", "飾る", "動詞"),
        ("deliver", "届ける", "動詞"),
        ("depend", "依存する", "動詞"),
        ("describe", "説明する", "動詞"),
        ("desire", "望む", "動詞"),
        ("educate", "教育する", "動詞"),
        ("encourage", "励ます", "動詞"),
        ("escape", "逃げる", "動詞"),
        ("examine", "調べる", "動詞"),
        ("exchange", "交換する", "動詞"),
        ("expand", "拡大する", "動詞"),
        ("fail", "失敗する", "動詞"),
        ("focus", "集中する", "動詞"),
        ("force", "強制する", "動詞"),
        ("gather", "集める", "動詞"),
        ("guide", "案内する", "動詞"),
        ("handle", "扱う", "動詞"),
        ("harm", "傷つける", "動詞"),
        ("identify", "特定する", "動詞"),
        ("imagine", "想像する", "動詞"),
        ("include", "含む", "動詞"),
        ("increase", "増やす", "動詞"),
        ("install", "設置する", "動詞"),
        ("involve", "含む", "動詞"),
        ("manage", "管理する", "動詞"),
        ("measure", "測る", "動詞"),
        ("mention", "言及する", "動詞"),
        ("notice", "気づく", "動詞"),
        ("observe", "観察する", "動詞"),
        ("obtain", "得る", "動詞"),
        ("offer", "提供する", "動詞"),
        ("overcome", "克服する", "動詞"),
        ("perform", "行う", "動詞"),
        ("prepare", "準備する", "動詞"),
        ("prevent", "防ぐ", "動詞"),
        ("promote", "促進する", "動詞"),
        ("publish", "出版する", "動詞"),
        ("recognize", "認識する", "動詞"),
        ("recommend", "推薦する", "動詞"),
        ("reduce", "減らす", "動詞"),
        ("refuse", "断る", "動詞"),
        ("reject", "拒否する", "動詞"),
        ("remind", "思い出させる", "動詞"),
        ("remove", "取り除く", "動詞"),
        ("repair", "修理する", "動詞"),
        ("replace", "取り替える", "動詞"),
        ("select", "選ぶ", "動詞"),
        ("separate", "分ける", "動詞"),
        ("share", "共有する", "動詞"),
        ("solve", "解く", "動詞"),
        ("suggest", "提案する", "動詞"),
        # 名詞
        ("adventure", "冒険", "名詞"),
        ("agreement", "合意", "名詞"),
        ("amount", "量", "名詞"),
        ("career", "職業", "名詞"),
        ("challenge", "課題", "名詞"),
        ("choice", "選択", "名詞"),
        ("community", "地域社会", "名詞"),
        ("competition", "競争", "名詞"),
        ("condition", "状態", "名詞"),
        ("culture", "文化", "名詞"),
        ("decision", "決断", "名詞"),
        ("doubt", "疑い", "名詞"),
        ("effort", "努力", "名詞"),
        ("emotion", "感情", "名詞"),
        ("energy", "エネルギー", "名詞"),
        ("error", "誤り", "名詞"),
        ("goal", "目標", "名詞"),
        ("habit", "習慣", "名詞"),
        ("opinion", "意見", "名詞"),
        ("opportunity", "機会", "名詞"),
        ("patience", "忍耐", "名詞"),
        ("project", "プロジェクト", "名詞"),
        ("purpose", "目的", "名詞"),
        ("reaction", "反応", "名詞"),
        ("resource", "資源", "名詞"),
        # 形容詞
        ("anxious", "不安な", "形容詞"),
        ("brilliant", "優秀な", "形容詞"),
        ("clever", "賢い", "形容詞"),
        ("confident", "自信のある", "形容詞"),
        ("convenient", "便利な", "形容詞"),
        ("curious", "好奇心旺盛な", "形容詞"),
        ("determined", "断固とした", "形容詞"),
        ("efficient", "効率的な", "形容詞"),
        ("familiar", "親しみのある", "形容詞"),
        ("flexible", "柔軟な", "形容詞"),
        ("generous", "寛大な", "形容詞"),
        ("grateful", "感謝している", "形容詞"),
        ("reliable", "信頼できる", "形容詞"),
        ("suitable", "適切な", "形容詞"),
        ("valuable", "価値のある", "形容詞"),
        ("virtual", "仮想の", "形容詞"),
        # 副詞
        ("completely", "完全に", "副詞"),
        ("especially", "特に", "副詞"),
        ("generally", "一般的に", "副詞"),
        ("gradually", "徐々に", "副詞"),
        ("mainly", "主に", "副詞"),
        ("merely", "単に", "副詞"),
        ("nearly", "ほぼ", "副詞"),
        ("poorly", "不十分に", "副詞"),
        ("smoothly", "スムーズに", "副詞"),
        ("truly", "本当に", "副詞"),
    ],
    "2級": [
        # 動詞
        ("accommodate", "収容する", "動詞"),
        ("accumulate", "蓄積する", "動詞"),
        ("activate", "活性化する", "動詞"),
        ("advocate", "提唱する", "動詞"),
        ("allocate", "割り当てる", "動詞"),
        ("analyze", "分析する", "動詞"),
        ("anticipate", "予測する", "動詞"),
        ("assess", "評価する", "動詞"),
        ("associate", "関連付ける", "動詞"),
        ("attain", "達成する", "動詞"),
        ("attribute", "帰属させる", "動詞"),
        ("calculate", "計算する", "動詞"),
        ("characterize", "特徴づける", "動詞"),
        ("clarify", "明確にする", "動詞"),
        ("collaborate", "協力する", "動詞"),
        ("compensate", "補償する", "動詞"),
        ("comply", "従う", "動詞"),
        ("contemplate", "熟考する", "動詞"),
        ("coordinate", "調整する", "動詞"),
        ("cultivate", "培う", "動詞"),
        ("dedicate", "捧げる", "動詞"),
        ("define", "定義する", "動詞"),
        ("demonstrate", "実証する", "動詞"),
        ("designate", "指定する", "動詞"),
        ("detect", "検出する", "動詞"),
        ("determine", "決定する", "動詞"),
        ("differentiate", "区別する", "動詞"),
        ("distribute", "配布する", "動詞"),
        ("dominate", "支配する", "動詞"),
        ("eliminate", "排除する", "動詞"),
        ("emphasize", "強調する", "動詞"),
        ("enhance", "強化する", "動詞"),
        ("evaluate", "評価する", "動詞"),
        ("facilitate", "促進する", "動詞"),
        ("formulate", "策定する", "動詞"),
        ("generate", "生み出す", "動詞"),
        ("implement", "実施する", "動詞"),
        ("indicate", "示す", "動詞"),
        ("integrate", "統合する", "動詞"),
        ("interpret", "解釈する", "動詞"),
        ("maintain", "維持する", "動詞"),
        ("manipulate", "操作する", "動詞"),
        ("modify", "変更する", "動詞"),
        ("motivate", "動機づける", "動詞"),
        ("negotiate", "交渉する", "動詞"),
        ("participate", "参加する", "動詞"),
        ("perceive", "知覚する", "動詞"),
        ("persist", "持続する", "動詞"),
        ("predict", "予測する", "動詞"),
        ("preserve", "保存する", "動詞"),
        ("prioritize", "優先する", "動詞"),
        ("process", "処理する", "動詞"),
        ("pursue", "追求する", "動詞"),
        ("qualify", "資格を得る", "動詞"),
        ("reinforce", "強化する", "動詞"),
        ("restrict", "制限する", "動詞"),
        ("simulate", "シミュレートする", "動詞"),
        ("specify", "特定する", "動詞"),
        ("stimulate", "刺激する", "動詞"),
        ("substitute", "代替する", "動詞"),
        ("summarize", "要約する", "動詞"),
        ("sustain", "持続させる", "動詞"),
        ("transform", "変容させる", "動詞"),
        ("transmit", "送信する", "動詞"),
        ("validate", "検証する", "動詞"),
        ("verify", "確認する", "動詞"),
        # 名詞
        ("alternative", "代替案", "名詞"),
        ("analysis", "分析", "名詞"),
        ("approach", "アプローチ", "名詞"),
        ("argument", "議論", "名詞"),
        ("assessment", "評価", "名詞"),
        ("assumption", "仮定", "名詞"),
        ("authority", "権限", "名詞"),
        ("benefit", "利点", "名詞"),
        ("category", "カテゴリ", "名詞"),
        ("characteristic", "特徴", "名詞"),
        ("circumstance", "状況", "名詞"),
        ("compromise", "妥協", "名詞"),
        ("concept", "概念", "名詞"),
        ("conclusion", "結論", "名詞"),
        ("consequence", "結果", "名詞"),
        ("contribution", "貢献", "名詞"),
        ("controversy", "論争", "名詞"),
        ("decade", "10年", "名詞"),
        ("decline", "衰退", "名詞"),
        ("diversity", "多様性", "名詞"),
        ("element", "要素", "名詞"),
        ("equilibrium", "均衡", "名詞"),
        ("factor", "要因", "名詞"),
        ("foundation", "基盤", "名詞"),
        ("framework", "枠組み", "名詞"),
        ("hypothesis", "仮説", "名詞"),
        ("ideology", "イデオロギー", "名詞"),
        ("implication", "含意", "名詞"),
        ("institution", "制度", "名詞"),
        ("legislation", "法律", "名詞"),
        ("mechanism", "仕組み", "名詞"),
        ("perspective", "視点", "名詞"),
        ("priority", "優先事項", "名詞"),
        ("probability", "確率", "名詞"),
        # 形容詞
        ("abstract", "抽象的な", "形容詞"),
        ("ambitious", "野心的な", "形容詞"),
        ("appropriate", "適切な", "形容詞"),
        ("comprehensive", "包括的な", "形容詞"),
        ("controversial", "論争的な", "形容詞"),
        ("dynamic", "活気のある", "形容詞"),
        ("ethical", "倫理的な", "形容詞"),
        ("fundamental", "根本的な", "形容詞"),
        ("gradual", "段階的な", "形容詞"),
        ("inevitable", "避けられない", "形容詞"),
        ("innovative", "革新的な", "形容詞"),
        ("intellectual", "知的な", "形容詞"),
        ("logical", "論理的な", "形容詞"),
        ("objective", "客観的な", "形容詞"),
        ("persistent", "粘り強い", "形容詞"),
        ("rational", "合理的な", "形容詞"),
        ("relevant", "関連のある", "形容詞"),
        ("sophisticated", "洗練された", "形容詞"),
        ("substantial", "かなりの", "形容詞"),
        ("theoretical", "理論的な", "形容詞"),
        ("universal", "普遍的な", "形容詞"),
        ("voluntary", "自発的な", "形容詞"),
    ],
    "準1級": [
        # 動詞
        ("alleviate", "緩和する", "動詞"),
        ("amplify", "拡大する", "動詞"),
        ("arbitrate", "仲裁する", "動詞"),
        ("aspire", "熱望する", "動詞"),
        ("assimilate", "同化する", "動詞"),
        ("augment", "増加させる", "動詞"),
        ("capitalize", "活用する", "動詞"),
        ("circumvent", "回避する", "動詞"),
        ("coerce", "強制する", "動詞"),
        ("compel", "強いる", "動詞"),
        ("conceive", "考案する", "動詞"),
        ("condone", "黙認する", "動詞"),
        ("consolidate", "統合する", "動詞"),
        ("contradict", "矛盾する", "動詞"),
        ("contend", "主張する", "動詞"),
        ("depict", "描写する", "動詞"),
        ("deplete", "枯渇させる", "動詞"),
        ("devise", "考案する", "動詞"),
        ("diminish", "減少させる", "動詞"),
        ("discern", "識別する", "動詞"),
        ("dispel", "払拭する", "動詞"),
        ("disrupt", "混乱させる", "動詞"),
        ("divert", "転換する", "動詞"),
        ("elaborate", "詳述する", "動詞"),
        ("embody", "体現する", "動詞"),
        ("encompass", "包含する", "動詞"),
        ("enlighten", "啓発する", "動詞"),
        ("evoke", "呼び起こす", "動詞"),
        ("exacerbate", "悪化させる", "動詞"),
        ("exploit", "利用する", "動詞"),
        ("foster", "育成する", "動詞"),
        ("galvanize", "刺激する", "動詞"),
        ("harness", "活用する", "動詞"),
        ("illuminate", "照らす", "動詞"),
        ("impede", "妨げる", "動詞"),
        ("impose", "課す", "動詞"),
        ("infer", "推論する", "動詞"),
        ("intervene", "介入する", "動詞"),
        ("invoke", "呼び起こす", "動詞"),
        ("liberate", "解放する", "動詞"),
        ("maximize", "最大化する", "動詞"),
        ("mediate", "調停する", "動詞"),
        ("minimize", "最小化する", "動詞"),
        ("mobilize", "動員する", "動詞"),
        ("monitor", "監視する", "動詞"),
        ("navigate", "航行する", "動詞"),
        ("obscure", "不明瞭にする", "動詞"),
        ("optimize", "最適化する", "動詞"),
        ("perpetuate", "永続させる", "動詞"),
        ("portray", "描写する", "動詞"),
        ("presume", "推定する", "動詞"),
        ("prohibit", "禁じる", "動詞"),
        ("reconcile", "和解させる", "動詞"),
        ("refine", "洗練させる", "動詞"),
        ("rehabilitate", "更生させる", "動詞"),
        ("replenish", "補充する", "動詞"),
        ("scrutinize", "精査する", "動詞"),
        ("suppress", "抑制する", "動詞"),
        ("synthesize", "統合する", "動詞"),
        ("terminate", "終わらせる", "動詞"),
        ("undermine", "損なう", "動詞"),
        ("yield", "生み出す", "動詞"),
        # 名詞
        ("accountability", "説明責任", "名詞"),
        ("ambiguity", "曖昧さ", "名詞"),
        ("analogy", "類似", "名詞"),
        ("autonomy", "自律性", "名詞"),
        ("benchmark", "基準", "名詞"),
        ("bureaucracy", "官僚制", "名詞"),
        ("coherence", "一貫性", "名詞"),
        ("commodity", "商品", "名詞"),
        ("competence", "能力", "名詞"),
        ("configuration", "設定", "名詞"),
        ("confrontation", "対立", "名詞"),
        ("consensus", "合意", "名詞"),
        ("credibility", "信頼性", "名詞"),
        ("delegation", "委任", "名詞"),
        ("deterioration", "悪化", "名詞"),
        ("dilemma", "ジレンマ", "名詞"),
        ("discourse", "言説", "名詞"),
        ("disparity", "格差", "名詞"),
        ("disruption", "混乱", "名詞"),
        ("distinction", "区別", "名詞"),
        ("dominance", "支配", "名詞"),
        ("endorsement", "支持", "名詞"),
        ("entrepreneur", "起業家", "名詞"),
        ("erosion", "侵食", "名詞"),
        ("exclusion", "排除", "名詞"),
        ("incentive", "誘因", "名詞"),
        ("inflation", "インフレ", "名詞"),
        ("initiative", "主導権", "名詞"),
        ("jurisdiction", "管轄", "名詞"),
        ("legitimacy", "正当性", "名詞"),
        ("methodology", "方法論", "名詞"),
        ("momentum", "勢い", "名詞"),
        ("obligation", "義務", "名詞"),
        ("paradox", "逆説", "名詞"),
        ("perseverance", "忍耐力", "名詞"),
        ("pragmatism", "実用主義", "名詞"),
        ("precedent", "先例", "名詞"),
        ("prejudice", "偏見", "名詞"),
        # 形容詞
        ("ambiguous", "曖昧な", "形容詞"),
        ("austere", "質素な", "形容詞"),
        ("coherent", "一貫した", "形容詞"),
        ("compatible", "互換性のある", "形容詞"),
        ("compelling", "説得力のある", "形容詞"),
        ("conducive", "助長する", "形容詞"),
        ("contentious", "論争的な", "形容詞"),
        ("cumbersome", "扱いにくい", "形容詞"),
        ("detrimental", "有害な", "形容詞"),
        ("diligent", "勤勉な", "形容詞"),
        ("eloquent", "雄弁な", "形容詞"),
        ("empathetic", "共感的な", "形容詞"),
        ("feasible", "実現可能な", "形容詞"),
        ("formidable", "恐ろしい", "形容詞"),
        ("holistic", "全体論的な", "形容詞"),
        ("incompatible", "相容れない", "形容詞"),
        ("indispensable", "不可欠な", "形容詞"),
        ("lucrative", "収益性の高い", "形容詞"),
        ("meticulous", "綿密な", "形容詞"),
        ("plausible", "もっともらしい", "形容詞"),
        ("pragmatic", "実用的な", "形容詞"),
        ("prevalent", "蔓延している", "形容詞"),
        ("resilient", "回復力のある", "形容詞"),
        ("rigorous", "厳格な", "形容詞"),
        ("skeptical", "懐疑的な", "形容詞"),
        ("tenacious", "粘り強い", "形容詞"),
        ("transparent", "透明な", "形容詞"),
        ("unprecedented", "前例のない", "形容詞"),
        ("versatile", "多才な", "形容詞"),
        ("viable", "実行可能な", "形容詞"),
        ("volatile", "不安定な", "形容詞"),
    ],
    "1級": [
        # 動詞
        ("accentuate", "強調する", "動詞"),
        ("acquiesce", "黙認する", "動詞"),
        ("adjudicate", "裁定する", "動詞"),
        ("admonish", "戒める", "動詞"),
        ("aggravate", "悪化させる", "動詞"),
        ("alienate", "疎外する", "動詞"),
        ("allude", "ほのめかす", "動詞"),
        ("ameliorate", "改善する", "動詞"),
        ("annihilate", "全滅させる", "動詞"),
        ("antagonize", "敵対させる", "動詞"),
        ("apprehend", "逮捕する", "動詞"),
        ("ascertain", "確認する", "動詞"),
        ("assuage", "和らげる", "動詞"),
        ("atrophy", "萎縮する", "動詞"),
        ("attenuate", "弱める", "動詞"),
        ("capitulate", "降伏する", "動詞"),
        ("castigate", "厳しく批判する", "動詞"),
        ("circumscribe", "制限する", "動詞"),
        ("coalesce", "合体する", "動詞"),
        ("commend", "称賛する", "動詞"),
        ("concoct", "でっち上げる", "動詞"),
        ("confiscate", "没収する", "動詞"),
        ("conjecture", "推測する", "動詞"),
        ("connote", "暗示する", "動詞"),
        ("corroborate", "裏付ける", "動詞"),
        ("debilitate", "弱らせる", "動詞"),
        ("decapitate", "斬首する", "動詞"),
        ("defame", "中傷する", "動詞"),
        ("denigrate", "けなす", "動詞"),
        ("deprive", "奪う", "動詞"),
        ("desolate", "荒廃させる", "動詞"),
        ("deviate", "逸脱する", "動詞"),
        ("dissipate", "消散させる", "動詞"),
        ("elucidate", "解明する", "動詞"),
        ("emulate", "模倣する", "動詞"),
        ("encroach", "侵害する", "動詞"),
        ("enunciate", "はっきり述べる", "動詞"),
        ("equivocate", "あいまいに話す", "動詞"),
        ("eradicate", "根絶する", "動詞"),
        ("expedite", "促進する", "動詞"),
        ("extol", "絶賛する", "動詞"),
        ("fabricate", "捏造する", "動詞"),
        ("foment", "扇動する", "動詞"),
        ("impersonate", "なりすます", "動詞"),
        ("incite", "煽動する", "動詞"),
        ("inculcate", "教え込む", "動詞"),
        ("indoctrinate", "洗脳する", "動詞"),
        ("infiltrate", "潜入する", "動詞"),
        ("instigate", "扇動する", "動詞"),
        ("intimidate", "脅す", "動詞"),
        ("jeopardize", "危険にさらす", "動詞"),
        ("lament", "嘆く", "動詞"),
        ("liquidate", "清算する", "動詞"),
        ("mitigate", "軽減する", "動詞"),
        ("mollify", "なだめる", "動詞"),
        ("obstruct", "妨害する", "動詞"),
        ("ostracize", "追放する", "動詞"),
        ("perpetrate", "犯す", "動詞"),
        ("postulate", "仮定する", "動詞"),
        ("precipitate", "引き起こす", "動詞"),
        ("preempt", "先手を打つ", "動詞"),
        ("propagate", "広める", "動詞"),
        ("rectify", "是正する", "動詞"),
        ("reiterate", "繰り返す", "動詞"),
        ("relinquish", "手放す", "動詞"),
        ("repudiate", "否定する", "動詞"),
        ("retaliate", "報復する", "動詞"),
        ("sequester", "隔離する", "動詞"),
        ("sever", "切断する", "動詞"),
        ("subjugate", "征服する", "動詞"),
        ("subvert", "転覆させる", "動詞"),
        ("supersede", "取って代わる", "動詞"),
        ("vindicate", "正当性を証明する", "動詞"),
        ("waive", "放棄する", "動詞"),
        # 名詞
        ("aberration", "逸脱", "名詞"),
        ("acrimony", "辛辣さ", "名詞"),
        ("allegiance", "忠誠", "名詞"),
        ("ambivalence", "両価性", "名詞"),
        ("anarchy", "無政府状態", "名詞"),
        ("apprehension", "不安", "名詞"),
        ("archetype", "原型", "名詞"),
        ("benevolence", "善意", "名詞"),
        ("capitalism", "資本主義", "名詞"),
        ("catharsis", "浄化", "名詞"),
        ("chicanery", "ごまかし", "名詞"),
        ("circumspection", "用心深さ", "名詞"),
        ("culpability", "罪責", "名詞"),
        ("demagoguery", "扇動政治", "名詞"),
        ("despondency", "落胆", "名詞"),
        ("dialectic", "弁証法", "名詞"),
        ("diffidence", "内気", "名詞"),
        ("dilapidation", "荒廃", "名詞"),
        ("dissension", "不和", "名詞"),
        ("dogmatism", "独断主義", "名詞"),
        ("eloquence", "雄弁", "名詞"),
        ("empiricism", "経験主義", "名詞"),
        ("epistemology", "認識論", "名詞"),
        ("estrangement", "疎遠", "名詞"),
        ("euphemism", "婉曲表現", "名詞"),
        ("fanaticism", "狂信主義", "名詞"),
        ("frugality", "倹約", "名詞"),
        ("futility", "無益", "名詞"),
        ("genealogy", "系譜", "名詞"),
        ("hegemony", "覇権", "名詞"),
        ("homogeneity", "均質性", "名詞"),
        ("hyperbole", "誇張", "名詞"),
        ("hypocrisy", "偽善", "名詞"),
        ("iconoclasm", "偶像破壊", "名詞"),
        ("insolence", "傲慢さ", "名詞"),
        ("introspection", "内省", "名詞"),
        ("juxtaposition", "並置", "名詞"),
        ("magnanimity", "寛大さ", "名詞"),
        ("malevolence", "悪意", "名詞"),
        ("meritocracy", "実力主義", "名詞"),
        ("misanthropy", "人間嫌い", "名詞"),
        ("nihilism", "虚無主義", "名詞"),
        ("oppression", "抑圧", "名詞"),
        ("orthodoxy", "正統", "名詞"),
        ("pedagogy", "教育学", "名詞"),
        ("philanthropy", "博愛", "名詞"),
        ("prerogative", "特権", "名詞"),
        ("proliferation", "拡散", "名詞"),
        ("rationalism", "合理主義", "名詞"),
        ("retribution", "報復", "名詞"),
        ("xenophobia", "外国人嫌悪", "名詞"),
        # 形容詞
        ("abstruse", "難解な", "形容詞"),
        ("acrimonious", "辛辣な", "形容詞"),
        ("altruistic", "利他的な", "形容詞"),
        ("anachronistic", "時代錯誤な", "形容詞"),
        ("antithetical", "正反対の", "形容詞"),
        ("arcane", "難解な", "形容詞"),
        ("arduous", "困難な", "形容詞"),
        ("audacious", "大胆な", "形容詞"),
        ("bellicose", "好戦的な", "形容詞"),
        ("benevolent", "慈悲深い", "形容詞"),
        ("clandestine", "秘密の", "形容詞"),
        ("complacent", "自己満足の", "形容詞"),
        ("condescending", "見下す", "形容詞"),
        ("contemptuous", "軽蔑的な", "形容詞"),
        ("cryptic", "謎めいた", "形容詞"),
        ("cynical", "冷笑的な", "形容詞"),
        ("destitute", "極貧の", "形容詞"),
        ("didactic", "教訓的な", "形容詞"),
        ("diffident", "内気な", "形容詞"),
        ("dogmatic", "独断的な", "形容詞"),
        ("egregious", "とんでもない", "形容詞"),
        ("ephemeral", "短命な", "形容詞"),
        ("esoteric", "難解な", "形容詞"),
        ("facetious", "ふざけた", "形容詞"),
        ("fastidious", "几帳面な", "形容詞"),
        ("fervent", "熱烈な", "形容詞"),
        ("frugal", "倹約的な", "形容詞"),
        ("gregarious", "社交的な", "形容詞"),
        ("hegemonic", "覇権的な", "形容詞"),
        ("idiosyncratic", "特異な", "形容詞"),
        ("imperious", "横柄な", "形容詞"),
        ("incongruous", "不調和な", "形容詞"),
        ("indolent", "怠惰な", "形容詞"),
        ("infallible", "絶対確実な", "形容詞"),
        ("insidious", "陰険な", "形容詞"),
        ("introspective", "内省的な", "形容詞"),
        ("laconic", "簡潔な", "形容詞"),
        ("magnanimous", "寛大な", "形容詞"),
        ("malevolent", "悪意のある", "形容詞"),
        ("mendacious", "嘘をつく", "形容詞"),
        ("mercenary", "金目当ての", "形容詞"),
        ("nefarious", "凶悪な", "形容詞"),
        ("obstinate", "頑固な", "形容詞"),
        ("omniscient", "全知の", "形容詞"),
        ("parsimonious", "けちな", "形容詞"),
        ("pernicious", "有害な", "形容詞"),
        ("philanthropic", "博愛的な", "形容詞"),
        ("poignant", "心に刺さる", "形容詞"),
        ("pretentious", "気取った", "形容詞"),
        ("prodigious", "驚異的な", "形容詞"),
        ("pugnacious", "好戦的な", "形容詞"),
        ("recalcitrant", "反抗的な", "形容詞"),
        ("sanctimonious", "偽善的な", "形容詞"),
        ("sardonic", "冷笑的な", "形容詞"),
        ("truculent", "乱暴な", "形容詞"),
        ("vacuous", "空虚な", "形容詞"),
        ("vehement", "激烈な", "形容詞"),
        ("vindictive", "執念深い", "形容詞"),
    ],
}

new_entries = []
added_counts = {}

for level, word_list in candidates.items():
    count = 0
    for english, japanese, category in word_list:
        if english.lower() not in existing:
            existing.add(english.lower())
            new_entries.append({
                "id": str(uuid.uuid4()),
                "english": english,
                "japanese": japanese,
                "category": category,
                "level": level,
            })
            count += 1
        if count >= 100:
            break
    added_counts[level] = count

for level, count in added_counts.items():
    print(f"{level}: {count}語追加")

words.extend(new_entries)
print(f"合計: {len(words)}語")

output = json.dumps(words, ensure_ascii=False, indent=2)
with open(WATCH_JSON, "w", encoding="utf-8") as f:
    f.write(output)

with open(IOS_JSON, "w", encoding="utf-8") as f:
    f.write(output)

print("完了: Watch・iOS 両方の words.json を更新しました")
